version: '3'

services:
  gdbserver:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: keyframe_dev
    security_opt:
      - seccomp:unconfined
    container_name: keyframe_debug
    ports:
      - "7776:22"
      - "7777:7777"
      - "5000:5000"
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/home/debugger/code
    working_dir: /home/debugger/code
    hostname: debug
